server:
  port: 7579

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: test
feign:
  httpclient:
    enabled: true
